name = "xugou-app"
main = "backend/src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

minify = true # 生产环境压缩代码

# 设置自定义域名
routes = [
  { pattern = "monitor.gyokushou.ip-ddns.com", custom_domain = true },
]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou_db"
database_id = "9691d47e-f65e-48da-a284-6c558392e4ad"

[assets]
binding = "ASSETS"
directory = "frontend/dist"
not_found_handling = "single-page-application"

[version_metadata]
binding = "CF_VERSION_METADATA"
